# Generated by Django 4.2.7 on 2025-10-01 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Código único del proyecto (ej: LC1, COP8)', max_length=20, unique=True)),
                ('siglas', models.CharField(help_text='Siglas del proyecto', max_length=10)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del proyecto')),
                ('constructora', models.CharField(max_length=100)),
                ('fecha_entrega', models.DateField(help_text='Fecha de entrega de las viviendas')),
                ('fecha_termino_postventa', models.DateField(blank=True, help_text='120 días después de la entrega según DS49', null=True)),
                ('coordenadas_s', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Latitud (S)')),
                ('coordenadas_w', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Longitud (W)')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.comuna')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.region')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TipologiaVivienda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipología de Vivienda',
                'verbose_name_plural': 'Tipologías de Vivienda',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Código único de la vivienda dentro del proyecto', max_length=10)),
                ('familia_beneficiaria', models.CharField(help_text='Nombre de la familia', max_length=200)),
                ('estado', models.CharField(choices=[('construccion', 'En Construcción'), ('entregada', 'Entregada'), ('postventa', 'En Postventa'), ('terminada', 'Terminada')], default='construccion', max_length=20)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('fecha_inicio_postventa', models.DateField(blank=True, null=True)),
                ('fecha_termino_postventa', models.DateField(blank=True, null=True)),
                ('observaciones_generales', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viviendas', to='proyectos.proyecto')),
                ('tipologia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.tipologiavivienda')),
            ],
            options={
                'verbose_name': 'Vivienda',
                'verbose_name_plural': 'Viviendas',
                'ordering': ['proyecto', 'codigo'],
                'unique_together': {('proyecto', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(help_text='Ej: Estar-comedor, Cocina, Dormitorio 1', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('elementos_disponibles', models.JSONField(default=list, help_text='Lista de elementos que pueden tener observaciones en este recinto')),
                ('activo', models.BooleanField(default=True)),
                ('tipologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recintos', to='proyectos.tipologiavivienda')),
            ],
            options={
                'verbose_name': 'Recinto',
                'verbose_name_plural': 'Recintos',
                'ordering': ['tipologia__codigo', 'codigo'],
                'unique_together': {('tipologia', 'codigo')},
            },
        ),
    ]
