# Generated by Django 4.2.7 on 2025-10-03 16:20

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_beneficiario_vivienda_beneficiario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiario',
            options={'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'], 'verbose_name': 'Beneficiario', 'verbose_name_plural': 'Beneficiarios'},
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='apellido_paterno',
            field=models.CharField(default='', max_length=100, verbose_name='Apellido Paterno'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='telefonos',
            field=models.CharField(blank=True, help_text='Puede ingresar más de un teléfono, separados por coma.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
