# Generated by Django 4.2.7 on 2025-10-03 18:50

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_beneficiario_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='telefonos',
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[core.validators.validar_rut]),
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='proyectos.beneficiario')),
            ],
            options={
                'verbose_name': 'Teléfono',
                'verbose_name_plural': 'Teléfonos',
            },
        ),
    ]
