# Generated by Django 4.2.7 on 2025-10-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_normalizar_nombres'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telefono',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
