# Generated by Django 4.2.7 on 2025-10-11 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_beneficiario_activo_telefono_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='beneficiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viviendas', to='proyectos.beneficiario', unique=True),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='familia_beneficiaria',
            field=models.CharField(blank=True, help_text='Nombre de la familia', max_length=200, null=True),
        ),
    ]
