# Generated by Django 4.2.7 on 2025-10-11 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_alter_vivienda_beneficiario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='beneficiario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vivienda', to='proyectos.beneficiario'),
        ),
    ]
