# Generated by Django 4.2.7 on 2025-10-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_alter_vivienda_beneficiario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recinto',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vivienda',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='numero',
            field=models.CharField(help_text='Formato recomendado: +56 9 1234 5678', max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AddIndex(
            model_name='beneficiario',
            index=models.Index(fields=['rut'], name='proyectos_b_rut_ebb64b_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiario',
            index=models.Index(fields=['email'], name='proyectos_b_email_a2fc01_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiario',
            index=models.Index(fields=['apellido_paterno', 'apellido_materno', 'nombre'], name='proyectos_b_apellid_1971c9_idx'),
        ),
        migrations.AddIndex(
            model_name='recinto',
            index=models.Index(fields=['tipologia', 'activo'], name='proyectos_r_tipolog_249118_idx'),
        ),
        migrations.AddIndex(
            model_name='telefono',
            index=models.Index(fields=['numero'], name='proyectos_t_numero_12bb69_idx'),
        ),
        migrations.AddIndex(
            model_name='vivienda',
            index=models.Index(fields=['proyecto', 'tipologia'], name='proyectos_v_proyect_ecd871_idx'),
        ),
        migrations.AddIndex(
            model_name='vivienda',
            index=models.Index(fields=['estado', 'fecha_entrega'], name='proyectos_v_estado_afacbc_idx'),
        ),
        migrations.AddIndex(
            model_name='vivienda',
            index=models.Index(fields=['beneficiario'], name='proyectos_v_benefic_56be0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='recinto',
            constraint=models.UniqueConstraint(fields=('tipologia', 'codigo'), name='uniq_recinto_tipologia_codigo'),
        ),
        migrations.AddConstraint(
            model_name='vivienda',
            constraint=models.UniqueConstraint(fields=('proyecto', 'codigo'), name='uniq_vivienda_proyecto_codigo'),
        ),
        migrations.AddConstraint(
            model_name='vivienda',
            constraint=models.CheckConstraint(check=models.Q(('fecha_entrega__isnull', True), ('fecha_inicio_postventa__isnull', True), ('fecha_inicio_postventa__gte', models.F('fecha_entrega')), _connector='OR'), name='chk_fecha_postventa_despues_entrega'),
        ),
        migrations.AddConstraint(
            model_name='vivienda',
            constraint=models.CheckConstraint(check=models.Q(('fecha_termino_postventa__isnull', True), ('fecha_inicio_postventa__isnull', True), ('fecha_termino_postventa__gte', models.F('fecha_inicio_postventa')), _connector='OR'), name='chk_fecha_termino_despues_inicio'),
        ),
    ]
