# Generated by Django 4.2.7 on 2025-10-12 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_constructora_to_usuario'),
        ('proyectos', '0009_mejoras_seguridad_finales'),
    ]

    operations = [
        # Paso 1: Añadir campos temporales
        migrations.AddField(
            model_name='proyecto',
            name='constructora_legacy',
            field=models.CharField(blank=True, help_text='Campo legacy para compatibilidad', max_length=100),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='constructora_fk',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.constructora', verbose_name='Constructora Nueva'),
        ),
    ]
