# Generated by Django 4.2.7 on 2025-10-12 00:16

from django.db import migrations

def migrate_constructora_data(apps, schema_editor):
    """Migrar datos de constructora de CharField a ForeignKey"""
    Proyecto = apps.get_model('proyectos', 'Proyecto')
    Constructora = apps.get_model('core', 'Constructora')
    
    # Primero copiar los datos del campo original al legacy
    for proyecto in Proyecto.objects.all():
        if hasattr(proyecto, 'constructora') and proyecto.constructora:
            proyecto.constructora_legacy = str(proyecto.constructora)
            proyecto.save()
    
    # Obtener todos los proyectos y migrar a ForeignKey
    for proyecto in Proyecto.objects.all():
        nombre_constructora = proyecto.constructora_legacy or proyecto.constructora or "Sin Constructora"
        
        # Buscar o crear la constructora
        constructora, created = Constructora.objects.get_or_create(
            nombre=str(nombre_constructora),
            defaults={'activo': True}
        )
        
        # Asignar la constructora al proyecto
        proyecto.constructora_fk = constructora
        proyecto.save()
        
        if created:
            print(f"Creada constructora: {nombre_constructora}")

def reverse_migrate_constructora_data(apps, schema_editor):
    """Revertir la migración de datos"""
    Proyecto = apps.get_model('proyectos', 'Proyecto')
    
    for proyecto in Proyecto.objects.all():
        if proyecto.constructora_fk:
            proyecto.constructora_legacy = proyecto.constructora_fk.nombre
            proyecto.save()

class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_change_constructora_to_foreignkey'),
    ]

    operations = [
        migrations.RunPython(migrate_constructora_data, reverse_migrate_constructora_data),
    ]
