# Generated by Django 4.2.7 on 2025-10-12 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_constructora_to_usuario'),
        ('proyectos', '0011_migrate_constructora_data'),
    ]

    operations = [
        # Eliminar el campo original
        migrations.RemoveField(
            model_name='proyecto',
            name='constructora',
        ),
        # Renombrar el nuevo campo
        migrations.RenameField(
            model_name='proyecto',
            old_name='constructora_fk',
            new_name='constructora',
        ),
    ]
