# Generated by Django 4.2.7 on 2025-10-14 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usuario_apellido_materno_usuario_apellido_paterno_and_more'),
        ('proyectos', '0012_finalize_constructora_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipologiavivienda',
            name='metros_cuadrados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Metros cuadrados de la vivienda', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tipologiavivienda',
            name='numero_ambientes',
            field=models.PositiveIntegerField(blank=True, help_text='Número de ambientes', null=True),
        ),
        migrations.AddField(
            model_name='tipologiavivienda',
            name='tipo_estructura',
            field=models.CharField(blank=True, help_text='Tipo de estructura de la vivienda', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='constructora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.constructora', verbose_name='Constructora'),
        ),
    ]
