# Generated by Django 5.2.6 on 2025-10-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructora',
            name='rut',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='RUT'),
        ),
    ]
