# Generated by Django 4.2.7 on 2025-10-03 19:35

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_constructora_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='region',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='constructora',
            name='rut',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, validators=[core.validators.validar_rut], verbose_name='RUT'),
        ),
    ]
