# Generated by Django 4.2.7 on 2025-10-03 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comuna_activo_region_activo_alter_constructora_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionObservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_vencimiento_normal', models.IntegerField(default=120, help_text='Días por defecto para observaciones normales', verbose_name='Días de vencimiento (Normal)')),
                ('horas_vencimiento_urgente', models.IntegerField(default=48, help_text='Horas por defecto para observaciones urgentes', verbose_name='Horas de vencimiento (Urgente)')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Configuración de Observación',
                'verbose_name_plural': 'Configuración de Observaciones',
            },
        ),
    ]
