# Generated by Django 4.2.7 on 2025-10-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracionobservacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('SERVIU', 'SERVIU'), ('CONSTRUCTORA', 'Empresa Constructora'), ('TECHO', 'TECHO Chile'), ('ADMINISTRADOR', 'Administrador Sistema'), ('FAMILIA', 'Familia Beneficiaria')], max_length=50, unique=True),
        ),
    ]
