# Generated by Django 4.2.7 on 2025-10-04 14:57

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_rol_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, db_index=True, help_text='RUT del usuario (para familias beneficiarias). Ej: 12345678-9', max_length=12, null=True, unique=True, validators=[core.validators.validar_rut], verbose_name='RUT'),
        ),
    ]
