# Generated by Django 4.2.7 on 2025-10-12 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usuario_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='constructora',
            field=models.ForeignKey(blank=True, help_text='Constructora asociada (solo para usuarios con rol Constructora)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.constructora'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='empresa',
            field=models.CharField(blank=True, help_text='Para usuarios de constructoras (campo legacy, usar constructora)', max_length=200),
        ),
    ]
