# Generated by Django 4.2.7 on 2025-10-13 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '__latest__'),
        ('core', '__latest__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliarBeneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('parentesco', models.CharField(choices=[('conyuge', 'Cónyuge'), ('hijo', 'Hijo/a'), ('padre', 'Padre'), ('madre', 'Madre'), ('hermano', 'Hermano/a'), ('otro', 'Otro')], max_length=20, verbose_name='Parentesco')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Familiar del Beneficiario',
                'verbose_name_plural': 'Familiares de Beneficiarios',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='ActaRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acta', models.CharField(help_text='Número único del acta (ej: ACT-2025-001)', max_length=50, unique=True, verbose_name='Número de Acta')),
                ('fecha_entrega', models.DateTimeField(verbose_name='Fecha y Hora de Entrega')),
                ('lugar_entrega', models.CharField(help_text='Dirección exacta donde se realiza la entrega', max_length=200, verbose_name='Lugar de Entrega')),
                ('representante_techo', models.CharField(max_length=100, verbose_name='Representante TECHO')),
                ('cargo_representante', models.CharField(max_length=100, verbose_name='Cargo del Representante')),
                ('rut_representante', models.CharField(max_length=12, verbose_name='RUT del Representante')),
                ('telefono_representante', models.CharField(max_length=20, verbose_name='Teléfono del Representante')),
                ('jefe_construccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jefe de Construcción')),
                ('numero_voluntarios', models.PositiveIntegerField(default=0, verbose_name='Número de Voluntarios')),
                ('estado_estructura', models.BooleanField(default=True, help_text='True = Conforme, False = Con observaciones', verbose_name='Estado Estructura')),
                ('estado_instalaciones', models.BooleanField(default=True, help_text='True = Conforme, False = Con observaciones', verbose_name='Estado Instalaciones')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones detectadas durante la entrega', null=True, verbose_name='Observaciones')),
                ('plazo_correcciones', models.PositiveIntegerField(default=30, help_text='Días calendario para subsanar observaciones', verbose_name='Plazo para Correcciones (días)')),
                ('superficie_construida', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Superficie Construida (m²)')),
                ('numero_ambientes', models.PositiveIntegerField(verbose_name='Número de Ambientes')),
                ('tipo_estructura', models.CharField(choices=[('madera', 'Madera'), ('metalica', 'Metálica'), ('mixta', 'Mixta'), ('hormigon', 'Hormigón')], max_length=20, verbose_name='Tipo de Estructura')),
                ('tiene_electricidad', models.BooleanField(default=False)),
                ('tiene_agua_potable', models.BooleanField(default=False)),
                ('tiene_alcantarillado', models.BooleanField(default=False)),
                ('entregado_beneficiario', models.BooleanField(default=False, verbose_name='Entregado al Beneficiario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.beneficiario', verbose_name='Beneficiario')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.proyecto', verbose_name='Proyecto')),
                ('vivienda', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='acta_recepcion', to='proyectos.vivienda', verbose_name='Vivienda')),
            ],
            options={
                'verbose_name': 'Acta de Recepción',
                'verbose_name_plural': 'Actas de Recepción',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='familiarbeneficiario',
            name='acta_recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='reportes.actarecepcion'),
        ),
    ]
