# Generated by Django 4.2.7 on 2025-10-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familiarbeneficiario',
            options={'verbose_name': 'Familiar del Beneficiario', 'verbose_name_plural': 'Familiares del Beneficiario'},
        ),
        migrations.RemoveField(
            model_name='familiarbeneficiario',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='familiarbeneficiario',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='familiarbeneficiario',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familiarbeneficiario',
            name='nombre_completo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='familiarbeneficiario',
            name='parentesco',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='familiarbeneficiario',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
