# Generated by Django 4.2.7 on 2025-12-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_reportegenerado'),
    ]

    operations = [
        migrations.AddField(
            model_name='actarecepcion',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='PDF del acta almacenado en GCS', null=True, upload_to='actas/'),
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='archivo',
            field=models.FileField(blank=True, help_text='Archivo PDF almacenado en GCS', null=True, upload_to='reportes/'),
        ),
    ]
