# Generated by Django 5.2.6 on 2025-10-02 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='id_externo',
            field=models.CharField(blank=True, help_text='ID externo para importación', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='observacion',
            index=models.Index(fields=['id_externo'], name='incidencias_id_exte_f9207e_idx'),
        ),
    ]
