# Generated by Django 4.2.7 on 2025-10-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_observacion_id_externo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoobservacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seguimientoobservacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
