# Generated by Django 4.2.7 on 2025-10-03 20:14

from django.db import migrations, models
import incidencias.models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_estadoobservacion_activo_observacion_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='archivo_adjunto',
            field=models.FileField(blank=True, help_text='Archivo adjunto (PDF, DOC, DOCX, JPG, PNG, GIF - máx. 10MB)', null=True, upload_to='observaciones/%Y/%m/', validators=[incidencias.models.validate_file_size, incidencias.models.validate_file_extension]),
        ),
    ]
