# Generated by Django 4.2.7 on 2025-10-03 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import incidencias.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidencias', '0004_observacion_archivo_adjunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAdjuntoObservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo adjunto (PDF, DOC, DOCX, JPG, PNG, GIF - máx. 10MB)', upload_to='observaciones/%Y/%m/', validators=[incidencias.models.validate_file_size, incidencias.models.validate_file_extension])),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción opcional del archivo', max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='incidencias.observacion')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
