# Generated by Django 4.2.7 on 2025-10-11 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidencias', '0005_archivoadjuntoobservacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoobservacion',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='seguimientoobservacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='estadoobservacion',
            index=models.Index(fields=['activo'], name='incidencias_activo_97003e_idx'),
        ),
        migrations.AddIndex(
            model_name='estadoobservacion',
            index=models.Index(fields=['codigo', 'activo'], name='incidencias_codigo_de86b4_idx'),
        ),
        migrations.AddIndex(
            model_name='observacion',
            index=models.Index(fields=['estado', 'fecha_vencimiento'], name='incidencias_estado__d5b231_idx'),
        ),
        migrations.AddIndex(
            model_name='observacion',
            index=models.Index(fields=['proyecto', 'vivienda'], name='incidencias_proyect_4524ee_idx'),
        ),
        migrations.AddIndex(
            model_name='observacion',
            index=models.Index(fields=['asignado_a', 'estado'], name='incidencias_asignad_3e4d62_idx'),
        ),
        migrations.AddIndex(
            model_name='observacion',
            index=models.Index(fields=['fecha_ultima_actualizacion'], name='incidencias_fecha_u_17dd80_idx'),
        ),
        migrations.AddIndex(
            model_name='observacion',
            index=models.Index(fields=['prioridad', 'es_urgente'], name='incidencias_priorid_f79e06_idx'),
        ),
        migrations.AddIndex(
            model_name='observacion',
            index=models.Index(fields=['creado_por', 'fecha_creacion'], name='incidencias_creado__dacd03_idx'),
        ),
        migrations.AddIndex(
            model_name='seguimientoobservacion',
            index=models.Index(fields=['observacion', 'fecha'], name='incidencias_observa_98e1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='seguimientoobservacion',
            index=models.Index(fields=['usuario', 'fecha'], name='incidencias_usuario_b2c3bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='estadoobservacion',
            constraint=models.UniqueConstraint(fields=('codigo', 'nombre'), name='uniq_estado_codigo_nombre'),
        ),
        migrations.AddConstraint(
            model_name='observacion',
            constraint=models.CheckConstraint(check=models.Q(('fecha_cierre__isnull', True), ('fecha_cierre__gte', models.F('fecha_creacion')), _connector='OR'), name='chk_fecha_cierre_despues_creacion'),
        ),
        migrations.AddConstraint(
            model_name='observacion',
            constraint=models.CheckConstraint(check=models.Q(('fecha_vencimiento__isnull', True), ('fecha_vencimiento__gte', models.F('fecha_creacion__date')), _connector='OR'), name='chk_fecha_vencimiento_despues_creacion'),
        ),
    ]
